# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\CodingRepository\BigWork\alignDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 491)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(40, 10, 161, 31))
        self.label_title.setObjectName("label_title")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 50, 171, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.alignImgLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.alignImgLayout.setContentsMargins(0, 0, 0, 0)
        self.alignImgLayout.setObjectName("alignImgLayout")
        self.alignImgView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.alignImgView.setObjectName("alignImgView")
        self.alignImgLayout.addWidget(self.alignImgView)
        self.buttonUploadAlignImg = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonUploadAlignImg.setObjectName("buttonUploadAlignImg")
        self.alignImgLayout.addWidget(self.buttonUploadAlignImg)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 50, 171, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.refImgLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.refImgLayout.setContentsMargins(0, 0, 0, 0)
        self.refImgLayout.setObjectName("refImgLayout")
        self.refImgView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_2)
        self.refImgView.setObjectName("refImgView")
        self.refImgLayout.addWidget(self.refImgView)
        self.buttonUploadRefImg = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.buttonUploadRefImg.setObjectName("buttonUploadRefImg")
        self.refImgLayout.addWidget(self.buttonUploadRefImg)
        self.buttonAlign = QtWidgets.QPushButton(Dialog)
        self.buttonAlign.setGeometry(QtCore.QRect(60, 410, 121, 41))
        self.buttonAlign.setObjectName("buttonAlign")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 230, 171, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.alignedImgLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.alignedImgLayout.setContentsMargins(0, 0, 0, 0)
        self.alignedImgLayout.setObjectName("alignedImgLayout")
        self.alignedImgView = QtWidgets.QGraphicsView(self.verticalLayoutWidget_4)
        self.alignedImgView.setObjectName("alignedImgView")
        self.alignedImgLayout.addWidget(self.alignedImgView)
        self.buttonDoloadAlignedImg = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.buttonDoloadAlignedImg.setObjectName("buttonDoloadAlignedImg")
        self.alignedImgLayout.addWidget(self.buttonDoloadAlignedImg)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "图像配准（基于Opencv_Cuda）"))
        self.buttonUploadAlignImg.setText(_translate("Dialog", "上传待配准图片"))
        self.buttonUploadRefImg.setText(_translate("Dialog", "上传基准图片"))
        self.buttonAlign.setText(_translate("Dialog", "配准"))
        self.buttonDoloadAlignedImg.setText(_translate("Dialog", "下载配准后图片"))
