# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\CodingRepository\BigWork_bak\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 337)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(40, 10, 161, 31))
        self.label_title.setObjectName("label_title")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(280, 50, 171, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.align_View = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.align_View.setObjectName("align_View")
        self.verticalLayout.addWidget(self.align_View)
        self.Button_upload_algin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_upload_algin.setObjectName("Button_upload_algin")
        self.verticalLayout.addWidget(self.Button_upload_algin)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 50, 171, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.align_View_2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_2)
        self.align_View_2.setObjectName("align_View_2")
        self.verticalLayout_2.addWidget(self.align_View_2)
        self.Button_upload_ref = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.Button_upload_ref.setObjectName("Button_upload_ref")
        self.verticalLayout_2.addWidget(self.Button_upload_ref)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "图像配准（基于Opencv_Cuda）"))
        self.Button_upload_algin.setText(_translate("Dialog", "上传图片"))
        self.Button_upload_ref.setText(_translate("Dialog", "上传图片"))
